---
title: "script to add quarter to data-joined"
author: "Ken Howard"
date: "July 29, 2024"
format: html
editor: visual
---

```{r input file}
rm(list=ls(all.names=TRUE))
library(readr)
d <- (read.delim(file="~/wkshp-survey-analysis/data-joined/all_workshops.csv", sep = ",", stringsAsFactors = FALSE))
```

```{r write column}
quarter <- (d$workshop)
d <- data.frame(d, quarter)
rm(quarter)

month = substr(d$quarter, 6, 10)
d$quarter = substr(d$quarter, 0, 4)
month <- as.numeric(gsub('-', '', month))

quarter <- as.factor(cut(month, 
               breaks = c(0, 315, 625, 915, 1125, 1231),
                          include.lowest = T,
                          right = T))
levels(quarter) <- c("winter", "spring", "summer","fall","winter")
d$quarter <- paste(d$quarter, quarter)
rm(quarter, month)
summary(as.factor(d$quarter))
```

```{r output file}

write_csv(d, file= "~/wkshp-survey-analysis/data-joined/all_workshops_quarter.csv", na = "NA", append = FALSE, col_names = TRUE, quote = "needed")
```
